### PR TITLE
Allow opting out of view instrumentation hooks.

### PR DESCRIPTION
**Pull request by rwjblue**
The instrumentation of `render` / `rerender` events is MEGA SLOW right now (which we should definitely fix). As an example, running render 10 times with https://github.com/ef4/initial-render-perf:

* 154ms - mean with `logViewEvents` set to `false`
* 1437ms - mean with `logViewEvents` set to `true` (the current default)

### CODE REVIEW

**Comment by stefanpenner** [comment]
@rwjblue ya we need to improve this

cc @wycats

**Comment by rwjblue** [comment]
Just pushed a commit that should fix CI for Ember 1.11.

**Comment by rwjblue** [comment]
@stefanpenner - I'm happy to work through that (I believe the issue is https://github.com/emberjs/ember.js/issues/9865).  Can you comment over there about your proposed API tweak/change?

**Comment by rwjblue** [comment]
Any objection to landing this in the interim (while we work out fixing the perf impact of the instrumentation)?

**Comment by stefanpenner** [comment]
@rwjblue nope

**Comment by mike-north** [comment]
Thanks @rwjblue!

**Pull request merged**
